---
include:
  - board: blecorne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    shield: nice_view
  - board: blecorne_right
    shield: nice_view
  - board: blecorne_left
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
  - board: blecorne_right
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
